include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Theme Modernist
LUCI_PKGARCH:=all
PKG_NAME:=luci-theme-modern
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_MAINTAINER:=OSINTIA Team <osintia@example.com>

include ../luci.mk

# call BuildPackage - OpenWrt buildroot entry point
$(eval $(call BuildPackage,luci-theme-modern))
