include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Theme SaaS Dark
LUCI_PKGARCH:=all
PKG_NAME:=luci-theme-saas-dark
PKG_VERSION:=2.0.0
PKG_RELEASE:=1
PKG_MAINTAINER:=OSINTIA Team <osintia@example.com>

include ../luci.mk

# call BuildPackage - OpenWrt buildroot entry point
$(eval $(call BuildPackage,luci-theme-saas-dark))
